[build]
  # 指定发布目录（根据你的项目结构调整）
  publish = "public"

  # 构建命令
  command = "composer install && npm install && npm run production"

[build.environment]
  # 指定 PHP 和 Node.js 版本
  PHP_VERSION = "8.1"
  NODE_VERSION = "16"

[[plugins]]
  package = "netlify-plugin-composer-install"

[build.cache]
  # 缓存依赖项以加速构建
  paths = [
    "vendor",          # 缓存 PHP 依赖项
    "node_modules"     # 缓存 JavaScript 依赖项
  ]
